### ISSUE TITLE
How to deploy a Vizro app to Heroku?

### ISSUE THREAD

**Issue by pieterseyns** [mckinsey/vizro#150]
### Question

Could you provide an example on how the main.py or app.py should look like

In a Dash app , you typically have 

app= Dash ( __name__)
server=app.server

if __name__ == "__main__":
          ........

How is it supposed to work for Vizro?

### Code/Examples

My current code : 
app = Dash(__name__)
server = app.server

    
if __name__ == "__main__":
    app = Vizro().build(create_dashboard()).run( debug=True).  --> where create_dashboard create the most of the code to create the layout.

doesn't run
I get : dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called.

### vizro version

0.1.5

### Python version

3.9.18

### OS

MacOS

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by maxschulz-COL** [comment]
Hey @pieterseyns ,

thank you for posting this question, much appreciated!

Have you checked our guide on the different run methods and deployments: https://vizro.readthedocs.io/en/stable/pages/user_guides/run/#deployment-of-vizro-app

It seems to me that you may want to do:
```py
app = Vizro().build(dashboard)
server = app.dash.server
```

where `dashboard` could be you `create_dashboard` function.

Let us know if this did not work, and we can try further.

**Comment by antonymilne** [comment]
@pieterseyns by Heroic do you mean Heroku? If so then I can confirm this works well because I tried it out just yesterday 🙂 

Just to add to what @maxschulz-COL said, the basic things you need on Heroku are:
1. `Procfile` with `web: gunicorn app:server`
2. `requirements.txt` with `vizro` and `gunicorn`
3. Put your app in `app.py` exposing the underlying Flask server by doing `app = Vizro().build(dashboard); server = app.dash.server`
4. Custom assets go in `assets` folder and are picked up automatically
5. That’s it! Everything works straight away. Just push to Heroku and it will deploy

So the deployment process is really identical to Dash, just the `server` object in Vizro is nested one level deeper in `app.dash.server` rather than `app.server` as it is in Dash. I recommend these articles on deploying Dash which give further guidance and common pitfalls on deploying to Heroku:
* https://dash.plotly.com/deployment
* https://towardsdatascience.com/deploying-your-dash-app-to-heroku-the-magical-guide-39bd6a0c586c

**Comment by pieterseyns** [comment]
Thanks it is working now
