### ISSUE TITLE
Using multiple datasets for custom graphs

### ISSUE THREAD

**Issue by baniasbaabe** [mckinsey/vizro#164]
### Question

Is it possible to use multiple datasets for custom graphs? Right now, you have to create a function with `@capture` and `data_frame` as an argument, but what, if I want to use two datasets so it can also play nicely with the filter from vizro.

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by antonymilne** [comment]
Hi @baniasbaabe, great question! At the moment this is basically not possible, which was a deliberate decision in order to simplify functionality and align with the `plotly.express` interface.

Please could you explain exactly what you're trying to achieve here? It would be great to understand better so that we can assess whether this is something we should consider enabling in future. I've added the Feature Request label so we can see if anyone else wants to achieve the same thing also.

For now, the best way to do this would be to modify your code so that there's only one `data_frame` required, e.g. by doing a join of the multiple dataframes before they get passed into the plotting function. Would that work ok for you? There are some other solutions that _might_ be possible but I'd need to check, and they would be quite a bit more complicated than just handling one dataframe.

**Comment by baniasbaabe** [comment]
Thanks for the fast response! 

I have two datasets, ``historic` with historical time series and `predictions` with forecasts for the future. I wanted to plot the historic time series and the forecasted time series in one figure (and apply filters since the `timeseries_id` column is equal). But yeah like you said, it's more complicated for now.

**Comment by antonymilne** [comment]
Hmm, I feel like we should be able to get something working with just a single dataframe here. I don't quite understand what you're trying to plot or filter on though - please could you provide some example plotting code that you'd like to work? At the moment as I understand it there's two dataframes like this:

`historic`:
```
   timeseries_id  value
0              1      1
1              2      2
2              3      3
```

`predictions`:
```
   timeseries_id  value
0              1      4
1              2      5
2              3      6
```

**Comment by baniasbaabe** [comment]
Sorry for the late reply!

So, you have a `historic` dataframe like so:

```

Timestamp | TimeseriesID | y
-- | -- | --
2020-01-01 | 100 | 50.0
2020-01-02 | 100 | 60.5
2020-01-03 | 100 | 70.2
```

and a `predictions` dataframe like so:

```
Timestamp | TimeseriesID | Prediction
-- | -- | --
2020-01-04 | 100 | 20.0
2020-01-05 | 100 | 63.0
```

Therefore, you can plot both of the timeseries in one figure and filter based on the timeseriesid. Do you know what I mean? You could maybe append them but how about if you have prediction intervals in your prediction dataframe too (like upper and lower bound for your prediction).
