### ISSUE TITLE
False negative on hatch run test inside container environment

### ISSUE THREAD

**Issue by kaestro** [mckinsey/vizro#434]
### Description

Though I'm having no problem hosting vizro on my local server, the error on the test is coming out which I believe to be of false negative.

Or maybe it's something I needed to set for the environment which I have missed to, but still I believe it needs to be implemented inside the hatch to install the Google Chrome inside the linux system.

### Expected behavior

No errors

### Which package?

vizro

### Package version

Old: 0.1.16.dev0
New: 0.2.0

### Python version

3.8.17

### OS

ms windows 11, using vscode container

### How to Reproduce

1. Get containerized environment with vscode
2. cd vizro-core
3. hatch run test

### Output

![image](https://github.com/mckinsey/vizro/assets/32026095/b2f76c94-9a50-4d34-abd1-8652001b13f1)

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by l0uden** [comment]
Hi @kaestro!

Thanks for spotting this!

If you want to run integration tests (which is a part of hatch run tests command) you should install Chrome manually. Given the difficulties with creating a process to automatically install Chrome on the range of operating systems that users might be using, it would make most sense to add this step to manually install Chrome to the contribution documentation [here](https://vizro.readthedocs.io/en/stable/pages/development/contributing/?h=tests#testing). Or you can just raise a ticket for the docs change if you have limited time to contribute.

(You can run also unit tests separately using `hatch run test-unit` command - and for the docs change all you need is to check the linting by using `hatch run lint`)

**Comment by kaestro** [comment]
I think my I idea was short-sighted after reading your description.

And like you've just said, adding that to the documentation will perfectly make sense!

Thank you.

**Comment by antonymilne** [comment]
Just for more context, we use [chromedriver-autoinstaller](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller) to install chromedriver for running integration tests locally, because it's fiddly to install manually. This should work so long as you have chrome installed.

As @l0uden said above though, chromedriver is only needed for the integration tests, and 99% of the time all you need to run locally is `hatch run test-unit` and not the full test suite that includes integration tests. So if it's not easy to run integration tests locally they're fine to ignore.
