### ISSUE TITLE
make available dash pages through vm.page() constructor

### ISSUE THREAD

**Issue by vks2** [mckinsey/vizro#531]
### Description

Hi. is there a way to implement vm.Page() constructor without the need of re-writing existing Dash code and breaking it into custom_components parts? for example i have a single-paged dash app working correctly. may I wrap it into vm.Page?
here's the example of my code:
```
app = Dash(__name__, external_stylesheets =[dbc.themes.BOOTSTRAP])
 
email_input = dbc.Row([
        dbc.Label("Email"
                , html_for="example-email-row"
                , width=2),
        dbc.Col(dbc.Input(
                type="email"
                , id="example-email-row"
                , placeholder="Enter email"
            ),width=10,
        )],className="mb-3"
)

user_input = dbc.Row([
        dbc.Label("Password", html_for="example-name-row", width=2),
        dbc.Col(
            dbc.Input(
                type="text"
                , id="example-name-row"
                , placeholder="Enter name"
                , maxLength = 80
            ),width=10
        )], className="mb-3"
)

message = dbc.Row([
        dbc.Label("Message", html_for="example-message-row", width=2)
        ,dbc.Col(
            dbc.Textarea(id = "example-message-row"
                , className="mb-3"
                , placeholder="Enter message"
                , required = True)
            , width=10)
        ], className="mb-3")

def contact_form():
    markdown = ''' # Send a message if you have a comment, question, or concern. Thank you!'''   
    form = html.Div([ dbc.Container([
            dcc.Markdown(markdown)
            , html.Br()
            , dbc.Card(
                dbc.CardBody([
                     dbc.Form([email_input
                        , user_input
                        , message])
                ,html.Div(id = 'div-button', children = [
                    dbc.Button('Submit'
                    , color = 'primary'
                    , id='button-submit'
                    , n_clicks=0)
                ]) #end div
                ])#end cardbody
            )#end card
            , html.Br()
            , html.Br()
        ])
        ])
    return form

app.layout = html.Div([contact_form()])
    
@app.callback(Output('div-button', 'children'),
     Input("button-submit", 'n_clicks')
     ,Input("example-email-row", 'value')
     ,Input("example-name-row", 'value')
     ,Input("example-message-row", 'value')
    )
def submit_message(n, email, name, message):
    port = 465  # For SSL
    sender_email = email
    receiver_email = '<your email address here>'
      
    # Create a secure SSL context
    context = ssl.create_default_context()       
    
    if n > 0:
        with smtplib.SMTP_SSL("smtp.gmail.com", port, context=context) as server:
            server.login("<you email address here>", '<you email password here>')
            server.sendmail(sender_email, receiver_email, message)
            server.quit()
        return [html.P("Message Sent")]
    else:
        return[dbc.Button('Submit', color = 'primary', id='button-submit', n_clicks=0)]
```

 
of course i may wrap dash app constructor like this
```kwargs = {
    'external_stylesheets': [dbc.themes.BOOTSTRAP]
}
app = Vizro(**kwargs)
```
but as a next step i need to rewrite wy bootstrap form working nice at Dash to Vizro page if i want an app with single entry point:(

**Comment by huong-li-nguyen** [comment]
Hello @vks2 👋 

Excellent question! Your initial thought was spot on - [custom components](https://vizro.readthedocs.io/en/stable/pages/user-guides/custom-components/#create-a-new-component) are indeed the way to go.
You do not need to change much of your Dash code. For this example, I've left your Dash code untouched and reused your `contact_form()` function only 👍  You still need to wrap your dash component inside a custom component to register it as a valid component for the `vm.Page`, but this doesn't require much code!

```
# 1. Create a new custom component
class CustomForm(vm.VizroBaseModel):
    """New custom component `Custom Form`."""

    type: Literal["custom_form"] = "custom_form"

    def build(self):
        return contact_form()


# 2. Add new component to the expected type - here, the selector of the parent components
vm.Page.add_type("components", CustomForm)

page = vm.Page(title="Custom Component", components=[CustomForm()])
dashboard = vm.Dashboard(pages=[page])
```

![Screenshot 2024-06-18 at 09 33 06](https://github.com/mckinsey/vizro/assets/90609403/49c21419-8a9f-4267-8b77-eb2e142f2d3d)


**To your second concern:** Vizro does not support plugging other Bootstrap themes into Vizro at the moment. However, we've also started creating our own Bootstrap theme and we already started converting our components to bootstrap step-by-step so that this feature might be enabled in the future 🤞. Currently, it's not an easy swap, but you need to overwrite CSS instead.

**Comment by vks2** [comment]
what a cool and timely answer!
i'll give it a test.
indeed ou guys wrote a lot of css and it's not compatible with dash bootstrap - the last one breaks some parts in your app. thanks much for this beautyfull project!

**Comment by huong-li-nguyen** [comment]
@vks2, we plan to remove all the custom CSS and have everything live in our Vizro bootstrap theme. We've already started converting; that's why you see a mix of custom CSS files and the vizro-bootstrap stylesheet😄 

I hope we finish the conversion soon, but as you know, this also requires switching all components to Bootstrap or providing a translation layer. I'll keep you posted if you are interested, but it's definitely already in progress 🚀 

Let me know if you have any other questions 👍

**Comment by antonymilne** [comment]
Just to add to what @huong-li-nguyen said above: in the near future there will be a new `Figure` model which will allow you put an arbitrary Dash component into a Vizro dashboard without needing to define your own custom model. It's really intended for components that are reactive to the filter/parameter controls on the LHS of the page, but in theory there's no reason you couldn't use it for a static component. This will also be useful for your questions in https://github.com/mckinsey/vizro/issues/533.

There's a couple of other ways of integrating existing Dash page(s) this which might also be useful for some people so let me note them here. They'll currently suffer from the same limitations in terms of bootstrap themes though.

If you have a Dash page outside a vizro app, you can just add it into the Dash page registry. This is quick and dirty but does the job if you're just looking to host everything on one route and don't care about using other vizro features on your Dash page.

```
import dash
from vizro import Vizro
import vizro.models as vm

# Normal vizro app
page = vm.Page(title="My first page", components=[vm.Card(text="Hello, Vizro!")])
dashboard = vm.Dashboard(pages=[page])
app = Vizro().build(dashboard)

# Add a custom page
dash.register_page("custom_page", layout="Blah blah blah", path="/custom_page")

app.run()
```

The other way that _might_ work is to follow an approach like https://github.com/mckinsey/vizro/issues/317#issuecomment-1963785133 which allows you to combine a Vizro app with an arbitrary Flask app. This is more generic than just combining with a Dash app, but if you use this method specifically with the Flask app that underlies a Dash app then you might run into issues with clashing global variables. Our current `Vizro` class isn't well setup to support this because it doesn't expose `init_app`, but maybe in the future this will become a possible route.

**Comment by vks2** [comment]
that's great news. but dash callbacks aren't fully impelemented by vizro (please note that there's no quite large project on dash that is working without callbacks), so it's quite a complex work, still do not know if you could handle it without any sad exceptions.  Flask example is also great, but here i do not know how it would be working in production, since flask  layer(and dash layer too if applicable) wouldn't be so primitive  - it have own routes, callbacks and css tricks. if someone gives a try with a flask login app on top of your vizro dashboard example - that would be really good and insightful because of complex logic of both components.
anyway thank you so much for detailed answers!
