### ISSUE TITLE
App doesn't scale on mobile browsers 

### ISSUE THREAD

**Issue by baffelli** [mckinsey/vizro#69]
### Description

First of all congratulations for the very good work! I wanted to try the demo you linked, but unfortunately the app page doesn't get scaled in mobile browsers. All you can see is the sidebar 
![Screenshot_20230926-201757](https://github.com/mckinsey/vizro/assets/25075981/91489de9-390f-4118-ba44-aa63f1ac0aa5)

### Expected behavior

The dashboard should be responsive and scale according to the screen size.

### vizro version

Latest

### Python version

-

### OS

Android 12

### How to Reproduce

1. Open the demo on a mobile browser

### Output

![Screenshot_20230926-201757](https://github.com/mckinsey/vizro/assets/25075981/a87a5b23-1e79-4881-8fc3-bf0565ed0f8a)

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by Joseph-Perkins** [comment]
thank you @baffelli ! (and for raising the issue - the described behaviour is clear to understand)

the current version is optimised for desktop first, so currently this is expected behaviour for mobile devices (including Android and iPhone)

optimisation for mobile is on the roadmap for future development, and a pathway is identified for enabling it, so that will be added once necessary prior dependencies have been implemented, though there is no fixed timeframe for them yet (and we'll be able to revert back here as/when that is implemented)

(thanks again for raising the issue - it is very much appreciated!)

**Comment by Mjboothaus** [comment]
Yes looks promising although mobile viewing is not viable currently (iPhone).

For inspiration Streamlit.io have done an awesome job at auto-scaling their presentation layer.

**Comment by huong-li-nguyen** [comment]
Hello guys,

Good news! 🗞️ 

This should look much better in the latest `vizro>=0.12.0` release. A default button has been added, letting you collapse/expand the side panel. It automatically collapses for portrait mode on mobile. Everything should also be scaled better now.

It's not our fully optimized mobile solution yet, but this should already be a significant improvement in the meantime 👍 

![IMG_2908](https://github.com/mckinsey/vizro/assets/90609403/bba3c9fb-c8b2-4288-b7f8-6bf72af55c82)
![IMG_2909](https://github.com/mckinsey/vizro/assets/90609403/91097585-a6cf-47eb-8b95-4f96dcb4c0dc)
![IMG_2910](https://github.com/mckinsey/vizro/assets/90609403/e8406921-7ef1-4f95-a9d0-e87f22bb87d9)
