### ISSUE TITLE
kaggle can't connect to local Dash app running on http://127.0.0.1:8050/

### ISSUE THREAD

**Issue by j215chic** [mckinsey/vizro#820]
### Which package?

vizro

### Package version

latest one imported into kaggle for some reason Vizro.__version__ not working

### Description
running on linux mint
 
`Linux deepthought 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

running code below in a kaggle notebook on linux mint ( ufw disabled) vpn turned off ( just in case),

**it says it's running but** there’s no output from `lsof -i :8050` so nothing is currently listening on port 8050.  I tested using jupyter lab notebook works well. This seems to be a kaggle issue

firewall is off 

`sudo ufw status Status: inactive`   

all the iptables are open

```
sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination     
```
here's the cell from kaggle

```
import pandas as pd
import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro
from vizro.tables import dash_ag_grid

# Load the data from the CSV file
df = pd.read_csv('/kaggle/input/test_data.csv')

page = vm.Page(
    title="Testing vizro dash ag grid ",
    components=[
        vm.AgGrid(
            title="Test ag grid",
            figure=dash_ag_grid(
                data_frame=df
            )
        ),
    ],
    controls=[vm.Filter(column="Symbol")],
)

dashboard = vm.Dashboard(pages=[page])

Vizro().build(dashboard).run(jupyter_mode="external")

# Vizro().build(dashboard).run(jupyter_mode="tab")  # https://vizro.readthedocs.io/en/stable/pages/user-guides/run/#jupyter

# Vizro().build(dashboard).run(debug=False)

```

### How to Reproduce

set up a kaggle notebook
use kaggle package manager to `pip install vizro`
run the cell

### Output

running the cell I get 

`Dash app running on http://127.0.0.1:8050/`

but either running tab or external I get 

```


Unable to connect

Firefox can’t establish a connection to the server at 127.0.0.1:8050.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.


```

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by antonymilne** [comment]
Hi @j215chic and thank you for the very clear clear bug report.

First of all I am curious how you are running kaggle since when I try doing this in the online notebook I can't execute `lsof` or similar commands. Are you somehow running the notebook locally rather than in the kaggle environment?

After quite a bit of playing around, I've found a possible solution to this using [ngrok](https://ngrok.com/). The steps are:

1. Sign up for a free account on ngrok
2. Generate an authtoken
3. Copy and paste this into a [kaggle secret](https://www.kaggle.com/discussions/product-feedback/114053) with key `ngrok_authtoken`
4. Setup a tunnel by executing this in a cell on kaggle. Don't execute this too many times or you'll hit your limit of 3 free simultaneous tunnels on ngrok and need to kill connections before you connect again (easy to do but an extra step that's easy to avoid).
    ```
    from kaggle_secrets import UserSecretsClient
    from pyngrok import ngrok
    
    ngrok.set_auth_token(UserSecretsClient().get_secret("ngrok_authtoken"))
    tunnel = ngrok.connect(port)
    ```
5. Run your Vizro dashboard code like this. I included the [`Vizro._reset` line](https://vizro.readthedocs.io/en/latest/pages/user-guides/run/#jupyter) so that you can re-run just this cell without needing to restart the kernel.
     ```
    import vizro.plotly.express as px
    from vizro import Vizro
    import vizro.models as vm
    
    Vizro._reset()
    
    df = px.data.iris()
    
    page = vm.Page(
        title="My first dashboard",
        components=[
            vm.Graph(id="scatter_chart", figure=px.scatter(df, x="sepal_length", y="petal_width", color="species")),
            vm.Graph(id="hist_chart", figure=px.histogram(df, x="sepal_width", color="species")),
        ],
        controls=[
            vm.Filter(column="species", selector=vm.Dropdown(value=["ALL"])),
        ],
    )
    
    dashboard = vm.Dashboard(pages=[page])
    
    
    app = Vizro().build(dashboard)
    app.run(host="0.0.0.0", jupyter_server_url=tunnel.public_url, jupyter_mode="tab")
    ```

You should find that all the various `jupyter_mode` options are supported this way.

The downside of ngrok is that without setting up more options (which maybe need a paid account, I'm not sure) the URL it generates will be publically viewable. If that's a problem then there's _maybe_ a way to get kaggle working without ngrok but I'd need to spend a few more hours playing around with it because they certainly don't make it easy 😅

**Comment by antonymilne** [comment]
Great to hear it, thanks for letting me know @j215chic! If you have any more questions do feel free to start a new issue.

Depending on what you need to do, you might also like to consider using [py.cafe](https://py.cafe/) which allows you to share a Vizro dashboard freely without any hosting. There's also various services out there with free and paid tiers for deploying, like Render, Huggingface and Ploomber. We hope to add some more docs to this in the future, but it's pretty easy to find and follow Dash examples for these, and doing it for vizro is [almost exactly the same](https://vizro.readthedocs.io/en/stable/pages/user-guides/run/#deployment).

**Comment by antonymilne** [comment]
Thank you for the kind comments @j215chic, that has made my day! The Vizro team know Adam pretty well now - his YouTube channel is awesome, and we've been lucky enough to make an appearance in a few of his videos so do take a look if you're interested! The [most recent one](https://www.youtube.com/watch?v=OZNAokBKT-M) is about [our visual vocabulary dashboard](https://huggingface.co/spaces/vizro/demo-visual-vocabulary).

**Comment by Coding-with-Adam** [comment]
Thank you @j215chic for your kind words. And thank you @antonymilne for assisting @j215chic with their issue.
