### ISSUE TITLE
Use datasets from data_manager for custom plots of plotly.graph_objects

### ISSUE THREAD

**Issue by Yairama** [mckinsey/vizro#98]
### What's the problem this feature will solve?

Currently only the plotly.expres can use the dataframes from data_manager directly. If we want to create a custom plot using plotly.graph_objects it's not possible due data_manager not have a public method to acces the added dataframes.

### Describe the solution you'd like

Add a wrapper for plotly.graph_objects as vizro.plotly.express has

### Alternative Solutions

A temporal solution could be add a public method to data_manager that returns a copy of the the dataframe to be used en go.

### Additional context

-

### Code of Conduct

- [X] I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by antonymilne** [comment]
Hello @Yairama and thank you for raising an issue 🙂 

I'm not sure I understand what you're trying to do here though. Please could you provide some code example to illustrate? Do you wish to refer to a dataframe by its name like `custom_graph(data_frame="iris", ...)`?

If so, I think what you need may already be possible since the behaviour that allows you to access a dataframe from the data manager by string lives in `capture("graph")`, which needs to be used for any custom graph. If you give some code then I should be able to show you how to do it.

**Comment by Yairama** [comment]
For sure!

```python

import vizro.plotly.express as px
import plotly.graph_objects as go
from vizro.managers import data_manager

df_waterfall = pd.DataFrame(
        {
            "measure": ["relative", "relative", "total", "relative", "relative", "total"],
            "x": ["Sales", "Consulting", "Net revenue", "Purchases", "Other expenses", "Profit before tax"],
            "text": ["+60", "+80", "", "-40", "-20", "Total"],
            "y": [60, 80, 0, -40, -20, 0],
        }
    )

data_magager["waterfall"] = df_waterfall.copy()
del df_waterfall

# Using plotly.express
# Here i can acces to waterfall dataframe from data_manager using the string "waterfall"
page_1 = vm.Page(
        title="px dash",
        components=[
            vm.Graph(
                id="scatter_chart",
                figure=px.scatter("waterfall", x="x", y="y"),
            )
        ]
    )

# Using plotly.graph_objects
# How can I access to waterfall dataframe that is inside of data_manager?
fig = go.Figure()
    fig.add_traces(
        go.Waterfall(
            measure=data_manager["waterfall"][measure], #Something like this I guess
            x=data_manager["waterfall"][[x], #Something like this I guess
            y=data_manager["waterfall"][[y], #Something like this I guess
            text=data_manager["waterfall"][[text], #Something like this I guess
            decreasing={"marker": {"color": "#ff5267"}},
            increasing={"marker": {"color": "#08bdba"}},
            totals={"marker": {"color": "#00b4ff"}},
        ),
    )

fig.update_layout(title=title)
page_2 = vm.Page(
   title="go_dash",
   components=[
       id="go_graph",
       figure=fig
   ]

)

# Build dash


```

**Comment by antonymilne** [comment]
This is possible exactly the same way as it is for standard `px` charts by just using `data_frame="waterfall"`. Following the [same waterfall chart example in the docs](https://vizro.readthedocs.io/en/latest/pages/user_guides/custom_charts/#new-waterfall-chart-based-on-gofigure), you could do this:

```python
data_manager["waterfall"] = waterfall_data()

page_0 = vm.Page(
    title="Custom chart",
    components=[
        vm.Graph(
            id="waterfall",
            figure=waterfall(
                data_frame="waterfall",
                measure="measure",
                x="x",
                y="y",
                text="text",
            ),
        ),
    ],
    controls=[
        vm.Filter(
            column="x", selector=vm.Dropdown(title="Financial categories", multi=True)
        ),
    ],
)
dashboard = vm.Dashboard(pages=[page_0])
```

I'm curious why you prefer to refer to dataset by name rather than doing `waterfall(data_frame=waterfall_data)` directly? It's a very legitimate thing to do but it would be very interesting to understand why you prefer this here if you don't mind explaining 🙂

**Comment by Yairama** [comment]
Now I understand thank you very much!

I thought that for custom plots you could only access the dataframes if you had an instance of them to pass as a parameter. :D

**Comment by antonymilne** [comment]
No worries! For custom plots the rules are the same as for normal ones - you can pass either `data_frame=pd.DataFrame()` directly or refer to something in the data manager with a string, like `data_frame="iris"`.
