### ISSUE TITLE
Have a component like Plotly Textarea to get text input from the user.

### ISSUE THREAD

**Issue by farshidbalan** [mckinsey/vizro#99]
### What's the problem this feature will solve?

Enabling users to input SQL queries for data retrieval can significantly enhance the utility of data connectors. This feature would allow for the generation of dynamic dashboards that can be customized according to user-defined queries as texts.

### Describe the solution you'd like

The following functionality from https://dash.plotly.com/dash-core-components/textarea#textarea-properties will suit text-based input.

    from dash import Dash, dcc, html, Input, Output, callback
    app = Dash(__name__)
    app.layout = html.Div([
      dcc.Textarea(
          id='textarea-example',
          value='Textarea content initialized\nwith multiple lines of text',
          style={'width': '100%', 'height': 300},
         ),
      html.Div(id='textarea-example-output', style={'whiteSpace': 'pre-line'})
     ])
  
    @callback(
      Output('textarea-example-output', 'children'),
      Input('textarea-example', 'value')
     )
    def update_output(value):
        return 'You have entered: \n{}'.format(value)

### Alternative Solutions

A different approach would be to have dropdown menus where the user could select the list of tables and filters and we generate the query in the backend. 

### Additional context

I was thinking of implementing a component like the following. I haven't tested it yet, but will work on such a solution.

    from typing import Optional
    from dash import ClientsideFunction, Input, Output, State, clientside_callback, dcc, html
    from pydantic import Field, validator

    from vizro.models import Action, VizroBaseModel
    from vizro.models._action._actions_chain import _action_validator_factory
    from vizro.models._models_utils import _log_call

    class Textarea(VizroBaseModel):
        """Textarea component for Vizro.

      Can be provided to [`Filter`][vizro.models.Filter] or
      [`Parameter`][vizro.models.Parameter]. Based on the underlying
      [`dcc.Textarea`](https://dash.plotly.com/dash-core-components/textarea).
  
      Args:
          value (Optional[str]): Default value for textarea. Defaults to `None`.
          title (Optional[str]): Title to be displayed. Defaults to `None`.
          actions (List[Action]): See [`Action`][vizro.models.Action]. Defaults to `[]`.
      """
  
      value: Optional[str] = Field(None, description="Default value for textarea.")
      title: Optional[str] = Field(None, description="Title to be displayed.")
      actions: List[Action] = []
  
      # Validator for actions, if needed
      _set_actions = _action_validator_factory("value")
  
      @_log_call
      def build(self):
          output = [Output(f"{self.id}_output", "children")]
          inputs = [Input(f"{self.id}_textarea", "value")]
  
          clientside_callback(
              ClientsideFunction(namespace="clientside", function_name="update_textarea_output"),
              output=output,
              inputs=inputs,
          )
  
          return html.Div(
              [
                  html.P(self.title) if self.title else None,
                  dcc.Textarea(
                      id=f"{self.id}_textarea",
                      value=self.value,
                      style={'width': '100%', 'height': 300},
                  ),
                  html.Div(
                      id=f"{self.id}_output",
                      style={'whiteSpace': 'pre-line'}
                  ),
              ],
              className="textarea_container",
              id=f"{self.id}_outer",
          )

### Code of Conduct

- [X] I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by huong-li-nguyen** [comment]
Hello @farshidbalan,

Thanks so much for raising the issue and proposing to create your custom component! ⭐ 

While we do not have the `TextArea` supported in our models library yet (we might do so in the future), what you describe is already possible by leveraging the functionality of our [custom components](https://vizro.readthedocs.io/en/latest/pages/user_guides/custom_components/). 

The custom components generally allow you to wrap any dash component inside the dashboard. For example, to get your model working, you only need to do these three explained in our user guide [here](https://vizro.readthedocs.io/en/latest/pages/user_guides/custom_components/#entirely-new-component):

1. Write out the code for your custom component embedding your dash component ✔️ 
2. Since the new model will be inserted into the controls argument of the Page, it will be part of the discriminated union describing the allowed types for that argument. 
- You need to add `type: Literal["text_area"] = "text_area"` to your model
- Execute `vm.Page.add_type("controls", Textarea)` after 
3. (Optional) Provide some CSS styling


Note: I've replaced the clientside callback just for quick demo purposes, but I recommend you use a clientside callback here instead.

```
"""Example to show custom component for text area."""
from typing import List, Literal, Optional

from dash import Input, Output, callback, dcc, html
from pydantic import Field

import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro
from vizro.models import Action, VizroBaseModel
from vizro.models._action._actions_chain import _action_validator_factory
from vizro.models._models_utils import _log_call


class Textarea(VizroBaseModel):
    type: Literal["text_area"] = "text_area"  # Note Change here
    value: Optional[str] = Field(None, description="Default value for textarea.")
    title: Optional[str] = Field(None, description="Title to be displayed.")
    actions: List[Action] = []

    # Validator for actions, if needed
    _set_actions = _action_validator_factory("value")

    @_log_call
    def build(self):
        @callback(Output(f"{self.id}_output", "children"), [Input(f"{self.id}", "value")])
        def update_text_area_output(value):
            if value:
                return "You have entered: \n{}".format(value)

        return html.Div(
            [
                html.P(self.title) if self.title else None,
                dcc.Textarea(
                    id=self.id,
                    value=self.value,
                    style={"width": "100%", "height": 300},
                ),
                html.Div(id=f"{self.id}_output", style={"whiteSpace": "pre-line"}),
            ],
            className="selector_container",  # Note Change here for better CSS
            id=f"{self.id}_outer",
        )


vm.Page.add_type("controls", Textarea)  # Note Change here

page = vm.Page(
    title="TextArea",
    components=[
        vm.Graph(
            figure=px.box(
                px.data.gapminder(),
                x="continent",
                y="lifeExp",
                color="continent",
                title="Distribution per continent",
            ),
        )
    ],
    controls=[Textarea(title="Input Query")],
)
dashboard = vm.Dashboard(pages=[page])
Vizro().build(dashboard).run()
```

This is optional but would make the component fit better into the general Vizro dashboard themes:
- I've additionally replaced the className for the outer Div to use `selector_container`, which makes it fit into the control panel
- You can add the following CSS code to a .css file and insert it into your assets folder as explained in our user guide on the [assets](https://vizro.readthedocs.io/en/latest/pages/user_guides/assets/#overwriting-global-css-properties) folder

```
textarea {
  background-color: var(--field-enabled);
}
```

This will then give you this result:
![Screenshot 2023-10-06 at 10 11 00](https://github.com/mckinsey/vizro/assets/90609403/55a7971d-2732-4e3a-a49d-429d708b79de)

So you were already very close to the final solution! 🚀 
I hope that helps, and let me know if you have any questions :)
